# Generated by Django 4.2.3 on 2023-07-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(max_length=120)),
                ('EmailName', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
