# Generated by Django 4.2.3 on 2023-07-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsignup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubadmin',
            name='CollegeName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
