# Generated by Django 4.2.3 on 2023-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsignup', '0002_clubadmin_collegename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubadmin',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
