# Generated by Django 4.2.3 on 2023-07-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsignup', '0003_alter_clubadmin_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubadmin',
            old_name='EmailName',
            new_name='Email',
        ),
    ]
